In [180]:
import time
import pandas as pd
import numpy as np

In [50]:
dt_comp1 = pd.read_csv("fpujimbaFika.csv", delimiter=";",header=None)
#dt_comp = pd.read_excel("fpujimbaFika.xlsx", sep=";",header=None)
#dt_comp = pd.read_fwf(r'fpujigabung.csv', delimiter=";",header=None)

In [51]:
#dt_comp=dtcomp.drop([1,2,3], axis=1)

In [52]:
dt_comp1.tail()

,0,1,2,3,4,5,6,7,8,9,...,872,873,874,875,876,877,878,879,880,881
25,Majoroside,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,Loganic,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
27,Glucoputran,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,Isoforskolin,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
29,Kaempferol-3,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [53]:
dt_comp1_id=dt_comp1[0]
del dt_comp1[0]
dt_comp1=pd.concat([dt_comp1_id,dt_comp1.astype('float')], axis=1)
dt_comp1.tail()

,0,1,2,3,4,5,6,7,8,9,...,872,873,874,875,876,877,878,879,880,881
25,Majoroside,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Loganic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Glucoputran,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Isoforskolin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,Kaempferol-3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [54]:
dt_comp2 = pd.read_excel("fpujimbaLinda.xlsx", sep=";",header=None)
dt_comp2.tail()

,0,1,2,3,4,5,6,7,8,9,...,872,873,874,875,876,877,878,879,880,881
387,Andrographolide type 2,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
388,Aloin,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
389,14-deoxy-11-oxoandrographolide,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
390,"14-deoxy-11,12-didehydroandrographolide2",0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
391,11-hydroxymutakone,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [55]:
dt_comp2_id=dt_comp2[0]
del dt_comp2[0]
dt_comp2=pd.concat([dt_comp2_id,dt_comp2.astype('float')], axis=1)
dt_comp2.tail()

,0,1,2,3,4,5,6,7,8,9,...,872,873,874,875,876,877,878,879,880,881
387,Andrographolide type 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
388,Aloin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
389,14-deoxy-11-oxoandrographolide,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
390,"14-deoxy-11,12-didehydroandrographolide2",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
391,11-hydroxymutakone,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
dt_comp0 = pd.read_csv("fplatih+LMT.csv", delimiter=";",header=None)
dt_comp0.tail()

,0,1,2,3,4,5,6,7,8,9,...,872,873,874,875,876,877,878,879,880,881
51,2165,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,4046,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,3955,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,65028,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,LMT,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [57]:
dt_comp0_id=dt_comp0[0]
del dt_comp0[0]
dt_comp0=pd.concat([dt_comp0_id,dt_comp0.astype('float')], axis=1)
dt_comp0.tail()

,0,1,2,3,4,5,6,7,8,9,...,872,873,874,875,876,877,878,879,880,881
51,2165,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,4046,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,3955,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,65028,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,LMT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [58]:
dt_comp_gabung = dt_comp1.append(pd.DataFrame(data = dt_comp2), ignore_index=True)

In [59]:
dt_comp_gabung=dt_comp_gabung.drop_duplicates(subset=[0])

In [60]:
dt_comp_gabung.tail()

,0,1,2,3,4,5,6,7,8,9,...,872,873,874,875,876,877,878,879,880,881
415,Andrographolide type 4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
416,Andrographolide type 3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
417,Andrographolide type 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
420,"14-deoxy-11,12-didehydroandrographolide2",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
421,11-hydroxymutakone,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [61]:
#dt_comp = dt_comp[0].str.split(";", n = 882, expand = True) 
#dt_comp.head()

In [181]:
dt_prot0 = pd.read_csv("targetuji_dip.csv", delimiter=";")

In [182]:
dt_prot0.tail()

,AA,RA,NA,DA,CA,EA,QA,GA,HA,IA,...,KV,MV,FV,PV,SV,TV,WV,YV,VV,#
140,0.006378,0.003189,0.003872,0.001595,0.005467,0.004784,0.000911,0.003645,0.003645,0.005695,...,0.002050,0.001139,0.000911,0.001595,0.002961,0.004556,0.004328,0.000228,0.002050,K4LC41_9BETC
141,0.004975,0.000000,0.001244,0.002488,0.002488,0.002488,0.002488,0.001244,0.004975,0.006219,...,0.002488,0.002488,0.002488,0.000000,0.004975,0.001244,0.002488,0.001244,0.001244,ACE2_HUMAN
142,0.006445,0.000000,0.005371,0.001074,0.002148,0.005371,0.000000,0.003222,0.004296,0.006445,...,0.004296,0.003222,0.002148,0.004296,0.003222,0.003222,0.003222,0.002148,0.004296,YP_009725307.1
143,0.003185,0.000000,0.006369,0.000000,0.003185,0.003185,0.000000,0.000000,0.000000,0.015924,...,0.000000,0.003185,0.003185,0.003185,0.000000,0.006369,0.003185,0.000000,0.006369,PLpro_SARS-CoV-2
144,0.006557,0.000000,0.000000,0.000000,0.006557,0.000000,0.006557,0.000000,0.003279,0.003279,...,0.006557,0.003279,0.006557,0.000000,0.006557,0.003279,0.000000,0.000000,0.006557,6LU7

In [188]:
dt_prot1 = pd.read_csv("newdip.csv", delimiter=";")
dt_prot1.tail()

,AA,RA,NA,DA,CA,EA,QA,GA,HA,IA,...,KV,MV,FV,PV,SV,TV,WV,YV,VV,#
370,0.004662,0.000000,0.004662,0.003108,0.000000,0.005439,0.000777,0.004662,0.000777,0.006216,...,0.003108,0.000777,0.003885,0.002331,0.003885,0.002331,0.003885,0.000000,0.002331,6VSB:A
371,0.004687,0.000000,0.004687,0.003906,0.000000,0.006250,0.000781,0.004687,0.000781,0.007031,...,0.003125,0.000781,0.003906,0.002344,0.003906,0.002344,0.003906,0.000000,0.002344,6VXX:A
372,0.006378,0.003189,0.003872,0.001595,0.005467,0.004784,0.000911,0.003645,0.003645,0.005695,...,0.002050,0.001139,0.000911,0.001595,0.002961,0.004556,0.004328,0.000228,0.002050,K4LC41_9BETC
373,0.006445,0.000000,0.005371,0.001074,0.002148,0.005371,0.000000,0.003222,0.004296,0.006445,...,0.004296,0.003222,0.002148,0.004296,0.003222,0.003222,0.003222,0.002148,0.004296,YP_009725307.1
374,0.003185,0.000000,0.006369,0.000000,0.003185,0.003185,0.000000,0.000000,0.000000,0.015924,...,0.000000,0.003185,0.003185,0.003185,0.000000,0.006369,0.003185,0.000000,0.006369,PLpro_SARS-CoV-2

In [198]:
dt_prot = dt_prot0.append(pd.DataFrame(data = dt_prot1), ignore_index=True,sort=False)
dt_prot.head()

,AA,RA,NA,DA,CA,EA,QA,GA,HA,IA,...,MV,FV,PV,SV,TV,WV,YV,VV,#,key
0,0.000000,0.004938,0.000000,0.000000,0.0,0.004938,0.007407,0.002469,0.004938,0.002469,...,0.002469,0.002469,0.000000,0.000000,0.002469,0.0,0.000000,0.004938,IF4A1_HUMAN,1
1,0.000000,0.002463,0.000000,0.000000,0.0,0.004926,0.009852,0.002463,0.004926,0.002463,...,0.000000,0.004926,0.000000,0.000000,0.004926,0.0,0.000000,0.004926,IF4A2_HUMAN,1
2,0.000000,0.004878,0.000000,0.000000,0.0,0.004878,0.004878,0.002439,0.002439,0.002439,...,0.000000,0.004878,0.000000,0.002439,0.002439,0.0,0.000000,0.004878,IF4A3_HUMAN,1
3,0.004975,0.002488,0.002488,0.003731,0.0,0.006219,0.006219,0.002488,0.001244,0.000000,...,0.002488,0.003731,0.002488,0.003731,0.002488,0.0,0.002488,0.006219,ACE2_HUMAN,1
4,0.000000,0.004175,0.000000,0.002088,0.0,0.004175,0.000000,0.006263,0.000000,0.000000,...,0.000000,0.002088,0.000000,0.002088,0.004175,0.0,0.000000,0.004175,AKT1_HUMAN,1

In [208]:
dt_prot_id=dt_prot["#"]
del(dt_prot["#"])

In [210]:
from sklearn.preprocessing import Normalizer
scaler= Normalizer(norm='max')
scaler.fit(dt_prot)
dt_prot_norm= scaler.transform(dt_prot)
dt_prot_norm=pd.DataFrame(dt_prot_norm)
dt_prot_norm.tail()

,0,1,2,3,4,5,6,7,8,9,...,391,392,393,394,395,396,397,398,399,400
515,0.004662,0.000000,0.004662,0.003108,0.000000,0.005439,0.000777,0.004662,0.000777,0.006216,...,0.003108,0.000777,0.003885,0.002331,0.003885,0.002331,0.003885,0.000000,0.002331,1.0
516,0.004687,0.000000,0.004687,0.003906,0.000000,0.006250,0.000781,0.004687,0.000781,0.007031,...,0.003125,0.000781,0.003906,0.002344,0.003906,0.002344,0.003906,0.000000,0.002344,1.0
517,0.006378,0.003189,0.003872,0.001595,0.005467,0.004784,0.000911,0.003645,0.003645,0.005695,...,0.002050,0.001139,0.000911,0.001595,0.002961,0.004556,0.004328,0.000228,0.002050,1.0
518,0.006445,0.000000,0.005371,0.001074,0.002148,0.005371,0.000000,0.003222,0.004296,0.006445,...,0.004296,0.003222,0.002148,0.004296,0.003222,0.003222,0.003222,0.002148,0.004296,1.0
519,0.003185,0.000000,0.006369,0.000000,0.003185,0.003185,0.000000,0.000000,0.000000,0.015924,...,0.000000,0.003185,0.003185,0.003185,0.000000,0.006369,0.003185,0.000000,0.006369,1.0

In [147]:
dt_prot_aac= dt_prot.iloc[:, :20]
dt_prot_aac.tail()

,A,R,N,D,C,E,Q,G,H,I,L,K,M,F,P,S,T,W,Y,V
534,0.078114,0.033250,0.047597,0.054430,0.030517,0.040310,0.033022,0.058073,0.018902,0.044864,0.097017,0.054430,0.021635,0.049875,0.038716,0.073787,0.071510,0.011387,0.044637,0.097928
535,0.063018,0.029851,0.064677,0.054726,0.013267,0.077944,0.049751,0.053068,0.036484,0.036484,0.099502,0.056385,0.034826,0.044776,0.044776,0.056385,0.053068,0.033167,0.046434,0.051410
536,0.062888,0.032609,0.068323,0.047360,0.023292,0.039596,0.051242,0.072981,0.020186,0.055124,0.083075,0.045031,0.008540,0.061335,0.048913,0.081522,0.073758,0.009317,0.041149,0.073758
537,0.068670,0.046137,0.060086,0.080472,0.031116,0.033262,0.030043,0.048283,0.028970,0.035408,0.089056,0.054721,0.026824,0.061159,0.032189,0.056867,0.065451,0.009657,0.062232,0.079399
538,0.055556,0.035948,0.068627,0.055556,0.039216,0.029412,0.045752,0.084967,0.022876,0.035948,0.094771,0.035948,0.032680,0.055556,0.042484,0.052288,0.078431,0.009804,0.035948,0.088235

In [148]:
dt_prot_ctdc= dt_prot.iloc[:, 20:41]
dt_prot_ctdc.tail()

,hydrophobicity.Group1,hydrophobicity.Group2,hydrophobicity.Group3,normwaalsvolume.Group1,normwaalsvolume.Group2,normwaalsvolume.Group3,polarity.Group1,polarity.Group2,polarity.Group3,polarizability.Group1,...,polarizability.Group3,charge.Group1,charge.Group2,charge.Group3,secondarystruct.Group1,secondarystruct.Group2,secondarystruct.Group3,solventaccess.Group1,solventaccess.Group2,solventaccess.Group3
534,0.263038,0.383739,0.353223,0.405147,0.360738,0.234115,0.397859,0.320200,0.281940,0.335914,...,0.234115,0.087679,0.817581,0.094739,0.376680,0.350717,0.272603,0.467775,0.263038,0.269187
535,0.333333,0.353234,0.313433,0.338308,0.379768,0.281924,0.359867,0.270315,0.369818,0.280265,...,0.281924,0.086235,0.781095,0.132670,0.447761,0.278607,0.273632,0.394693,0.333333,0.271973
536,0.284161,0.401398,0.314441,0.410714,0.371118,0.218168,0.355590,0.340062,0.304348,0.338509,...,0.218168,0.077640,0.835404,0.086957,0.343168,0.337733,0.319099,0.441770,0.284161,0.274068
537,0.304721,0.362661,0.332618,0.383047,0.327253,0.289700,0.394850,0.271459,0.333691,0.319742,...,0.289700,0.100858,0.785408,0.113734,0.377682,0.344421,0.277897,0.422747,0.304721,0.272532
538,0.271242,0.372549,0.356209,0.408497,0.362745,0.228758,0.392157,0.313725,0.294118,0.326797,...,0.228758,0.071895,0.843137,0.084967,0.352941,0.343137,0.303922,0.464052,0.271242,0.264706

In [149]:
dt_prot_ctdt= dt_prot.iloc[:, 41:62]
dt_prot_ctdt.tail()

,prop1.Tr1221,prop1.Tr1331,prop1.Tr2332,prop2.Tr1221,prop2.Tr1331,prop2.Tr2332,prop3.Tr1221,prop3.Tr1331,prop3.Tr2332,prop4.Tr1221,...,prop4.Tr2332,prop5.Tr1221,prop5.Tr1331,prop5.Tr2332,prop6.Tr1221,prop6.Tr1331,prop6.Tr2332,prop7.Tr1221,prop7.Tr1331,prop7.Tr2332
534,0.194989,0.189066,0.271526,0.293394,0.185421,0.166515,0.257859,0.224601,0.176310,0.288610,...,0.198178,0.141686,0.017312,0.154897,0.258087,0.189749,0.193394,0.252392,0.255353,0.131663
535,0.245847,0.215947,0.229236,0.279070,0.207641,0.209302,0.219269,0.269103,0.200997,0.257475,...,0.240864,0.144518,0.018272,0.210963,0.230897,0.239203,0.177741,0.285714,0.219269,0.176080
536,0.217560,0.196581,0.250194,0.309246,0.169386,0.164724,0.238539,0.233100,0.201243,0.299145,...,0.190365,0.122766,0.017871,0.148407,0.235431,0.216783,0.226107,0.259518,0.240870,0.154623
537,0.212675,0.205156,0.233083,0.237379,0.208378,0.195489,0.206230,0.266380,0.168636,0.240602,...,0.233083,0.162191,0.022556,0.175081,0.248120,0.193340,0.211600,0.269603,0.228786,0.148228
538,0.193443,0.236066,0.255738,0.278689,0.163934,0.170492,0.219672,0.291803,0.150820,0.295082,...,0.213115,0.121311,0.009836,0.127869,0.236066,0.193443,0.209836,0.275410,0.255738,0.154098

In [150]:
dt_prot_ctdd= dt_prot.iloc[:, 62:167]
dt_prot_ctdd.tail()

,prop1.G1.residue0,prop1.G1.residue25,prop1.G1.residue50,prop1.G1.residue75,prop1.G1.residue100,prop1.G2.residue0,prop1.G2.residue25,prop1.G2.residue50,prop1.G2.residue75,prop1.G2.residue100,...,prop7.G2.residue0,prop7.G2.residue25,prop7.G2.residue50,prop7.G2.residue75,prop7.G2.residue100,prop7.G3.residue0,prop7.G3.residue25,prop7.G3.residue50,prop7.G3.residue75,prop7.G3.residue100
534,0.227739,23.889775,45.912093,72.648599,99.886131,0.045548,24.664086,50.762924,75.427010,99.931678,...,0.227739,23.889775,45.912093,72.648599,99.886131,0.022774,25.324527,51.605557,75.427010,99.908905
535,0.663350,20.232172,45.936982,74.129353,99.004975,0.165837,28.689884,51.077944,77.611940,100.000000,...,0.663350,20.232172,45.936982,74.129353,99.004975,0.165837,26.865672,52.072968,78.606965,100.000000
536,1.086957,25.698758,50.155279,76.475155,100.000000,0.698758,26.319876,51.242236,75.388199,99.689441,...,1.086957,25.698758,50.155279,76.475155,100.000000,0.077640,23.214286,48.913043,72.981366,99.689441
537,0.321888,20.493562,47.746781,74.892704,100.000000,0.107296,27.145923,54.184549,75.214592,99.678112,...,0.321888,20.493562,47.746781,74.892704,100.000000,0.107296,28.326180,57.618026,80.257511,99.678112
538,1.307190,22.549020,46.405229,75.490196,100.000000,0.326797,30.392157,51.633987,70.261438,99.346405,...,1.307190,22.549020,46.405229,75.490196,100.000000,0.326797,26.143791,47.058824,68.300654,99.346405

In [151]:
dt_prot_paac1= dt_prot.iloc[:, 167:187]
dt_prot_paac1.tail()

,Xc1.A,Xc1.R,Xc1.N,Xc1.D,Xc1.C,Xc1.E,Xc1.Q,Xc1.G,Xc1.H,Xc1.I,Xc1.L,Xc1.K,Xc1.M,Xc1.F,Xc1.P,Xc1.S,Xc1.T,Xc1.W,Xc1.Y,Xc1.V
534,94.913694,40.400581,57.833708,66.135198,37.079985,48.978787,40.123865,70.562659,22.967454,54.513113,117.881147,66.135198,26.288049,60.600872,47.041772,89.656084,86.888921,13.835815,54.236396,118.988013
535,9.873878,4.677100,10.133717,8.574684,2.078711,12.212428,7.795167,8.314845,5.716456,5.716456,15.590334,8.834523,5.456617,7.015650,7.015650,8.834523,8.314845,5.196778,7.275489,8.055006
536,22.604552,11.720879,24.558031,17.023181,8.372056,14.232495,18.418523,26.232442,7.255782,19.813866,29.860333,16.185975,3.069754,22.046414,17.581318,29.302196,26.511511,3.348822,14.790632,26.511511
537,16.652188,11.188189,14.570665,19.514283,7.545523,8.065904,7.285332,11.708570,7.025142,8.586285,21.595807,13.269713,6.504761,14.830855,7.805713,13.790094,15.871617,2.341714,15.091046,19.254093
538,4.802136,3.107264,5.932050,4.802136,3.389743,2.542307,3.954700,7.344443,1.977350,3.107264,8.191879,3.107264,2.824786,4.802136,3.672221,4.519657,6.779486,0.847436,3.107264,7.626922

In [152]:
dt_prot_paac2= dt_prot.iloc[:, 187:217]
dt_prot_paac2.tail()

,Xc2.lambda.1,Xc2.lambda.2,Xc2.lambda.3,Xc2.lambda.4,Xc2.lambda.5,Xc2.lambda.6,Xc2.lambda.7,Xc2.lambda.8,Xc2.lambda.9,Xc2.lambda.10,...,Xc2.lambda.21,Xc2.lambda.22,Xc2.lambda.23,Xc2.lambda.24,Xc2.lambda.25,Xc2.lambda.26,Xc2.lambda.27,Xc2.lambda.28,Xc2.lambda.29,Xc2.lambda.30
534,0.024229,0.024970,0.024388,0.024445,0.024596,0.024573,0.023370,0.023881,0.024498,0.024516,...,0.023777,0.023736,0.024067,0.024042,0.024233,0.023815,0.023540,0.024581,0.023828,0.023941
535,0.026021,0.026256,0.024765,0.023500,0.025168,0.024856,0.023154,0.025257,0.025362,0.024410,...,0.024613,0.024756,0.024148,0.025199,0.024554,0.023132,0.024701,0.025072,0.025616,0.025272
536,0.024285,0.025225,0.023499,0.023551,0.024008,0.024428,0.023582,0.023945,0.023665,0.023701,...,0.023694,0.024046,0.024760,0.023859,0.024653,0.024845,0.022532,0.023180,0.024130,0.024999
537,0.024603,0.026472,0.024060,0.025308,0.024722,0.026229,0.023863,0.024557,0.024892,0.024936,...,0.023362,0.024421,0.024701,0.024124,0.024537,0.024475,0.023487,0.025516,0.025637,0.024120
538,0.024657,0.024595,0.026270,0.024008,0.022187,0.025179,0.023355,0.023522,0.022286,0.023233,...,0.022676,0.024021,0.022053,0.024425,0.023855,0.024451,0.023342,0.023351,0.021879,0.025722

In [153]:
dt_prot_id=dt_prot['Unnamed: 217']

In [154]:
dt_prot_aac.describe()

,A,R,N,D,C,E,Q,G,H,I,L,K,M,F,P,S,T,W,Y,V
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,0.066133,0.052421,0.040419,0.050085,0.020848,0.063074,0.039280,0.067481,0.024565,0.051287,0.099135,0.058828,0.025918,0.045824,0.056275,0.070419,0.053815,0.013534,0.032410,0.068249
std,0.021807,0.019425,0.015505,0.013942,0.011048,0.020061,0.014231,0.023944,0.010067,0.018530,0.027569,0.022913,0.009807,0.016080,0.021148,0.023445,0.015716,0.007131,0.011453,0.017331
min,0.022546,0.000000,0.000000,0.000000,0.000000,0.014320,0.000000,0.000000,0.000000,0.000000,0.010417,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,0.052525,0.041200,0.029887,0.042245,0.013586,0.050707,0.029326,0.052817,0.017085,0.038732,0.083038,0.044856,0.019453,0.034432,0.044649,0.056361,0.045053,0.008734,0.025871,0.056032
50%,0.063260,0.049863,0.039409,0.050279,0.019694,0.062500,0.038462,0.063043,0.024242,0.049689,0.097017,0.058201,0.025614,0.043912,0.054596,0.067961,0.052893,0.012862,0.032184,0.067890
75%,0.076851,0.060717,0.048780,0.057029,0.026455,0.075630,0.047638,0.078805,0.030568,0.062053,0.117671,0.070839,0.032680,0.056264,0.065301,0.080957,0.062167,0.017575,0.039111,0.080504
max,0.189189,0.194656,0.106061,0.131944,0.091549,0.128540,0.095299,0.177866,0.074380,0.135135,0.227848,0.156250,0.066667,0.121495,0.195122,0.202462,0.130000,0.037190,0.069124,0.128834

In [155]:
dt_prot_ctdc.describe()

,hydrophobicity.Group1,hydrophobicity.Group2,hydrophobicity.Group3,normwaalsvolume.Group1,normwaalsvolume.Group2,normwaalsvolume.Group3,polarity.Group1,polarity.Group2,polarity.Group3,polarizability.Group1,...,polarizability.Group3,charge.Group1,charge.Group2,charge.Group3,secondarystruct.Group1,secondarystruct.Group2,secondarystruct.Group3,solventaccess.Group1,solventaccess.Group2,solventaccess.Group3
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,...,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,0.304107,0.371099,0.324795,0.385057,0.361444,0.253499,0.357204,0.314123,0.328672,0.307934,...,0.253499,0.111249,0.775593,0.113159,0.429354,0.285967,0.284679,0.432492,0.304107,0.263402
std,0.050880,0.048302,0.050956,0.050365,0.039554,0.035779,0.053576,0.051771,0.050764,0.041430,...,0.035779,0.028010,0.047077,0.026603,0.048838,0.046764,0.040977,0.050920,0.050880,0.036583
min,0.147541,0.205882,0.121113,0.205882,0.179389,0.113636,0.151194,0.133803,0.147541,0.178744,...,0.113636,0.045455,0.557029,0.030675,0.265957,0.065574,0.117647,0.183206,0.147541,0.125000
25%,0.274720,0.344828,0.300339,0.353525,0.340611,0.233824,0.329683,0.284612,0.299625,0.282989,...,0.233824,0.093947,0.750799,0.096045,0.400073,0.258857,0.258785,0.406813,0.274720,0.240949
50%,0.304082,0.368159,0.323077,0.380282,0.362745,0.253801,0.358696,0.307385,0.329684,0.306391,...,0.253801,0.108491,0.777202,0.113730,0.430311,0.287037,0.281669,0.431149,0.304082,0.265873
75%,0.333333,0.392980,0.353223,0.410533,0.384490,0.277778,0.386093,0.338182,0.360640,0.329074,...,0.277778,0.124303,0.806648,0.128845,0.458333,0.312043,0.304310,0.463440,0.333333,0.285171
max,0.531830,0.604345,0.551402,0.606978,0.515152,0.408397,0.598131,0.585912,0.563660,0.513496,...,0.408397,0.281167,0.893939,0.222222,0.588235,0.457944,0.432203,0.621622,0.531830,0.487805

In [156]:
dt_prot_ctdt.describe()

,prop1.Tr1221,prop1.Tr1331,prop1.Tr2332,prop2.Tr1221,prop2.Tr1331,prop2.Tr2332,prop3.Tr1221,prop3.Tr1331,prop3.Tr2332,prop4.Tr1221,...,prop4.Tr2332,prop5.Tr1221,prop5.Tr1331,prop5.Tr2332,prop6.Tr1221,prop6.Tr1331,prop6.Tr2332,prop7.Tr1221,prop7.Tr1331,prop7.Tr2332
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,...,539.000000,539.000000,535.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,0.218542,0.193701,0.236425,0.270707,0.193198,0.180569,0.218826,0.231911,0.198992,0.265122,...,0.217923,0.166482,0.027820,0.168679,0.235597,0.237550,0.162713,0.258601,0.226825,0.153642
std,0.040983,0.036266,0.040479,0.034525,0.036113,0.033296,0.040034,0.040956,0.038002,0.037826,...,0.034426,0.035248,0.013948,0.035672,0.036851,0.037545,0.034371,0.041570,0.036680,0.034344
min,0.092593,0.082345,0.067729,0.135593,0.083969,0.076923,0.061089,0.083333,0.086420,0.118644,...,0.092308,0.080574,0.000000,0.033333,0.066667,0.134328,0.063492,0.125000,0.086321,0.027778
25%,0.193899,0.172414,0.210305,0.250978,0.170200,0.159826,0.192062,0.208045,0.176310,0.243072,...,0.196631,0.144359,0.019276,0.149405,0.223216,0.215710,0.143093,0.233913,0.205689,0.134884
50%,0.217560,0.193617,0.234234,0.272727,0.188776,0.182540,0.219669,0.232759,0.196597,0.267254,...,0.219372,0.163121,0.025875,0.170732,0.237179,0.233216,0.160633,0.255624,0.229665,0.153846
75%,0.237592,0.217134,0.260163,0.289104,0.212719,0.202336,0.244997,0.257550,0.216112,0.288610,...,0.241232,0.184359,0.033410,0.189940,0.253783,0.258346,0.180851,0.286915,0.247171,0.171875
max,0.494253,0.325243,0.395062,0.389831,0.448276,0.322581,0.364198,0.383495,0.444444,0.388889,...,0.344086,0.413793,0.116866,0.267206,0.457627,0.432950,0.324074,0.398601,0.350000,0.440613

In [157]:
from sklearn.preprocessing import Normalizer
scaler= Normalizer(norm='max')
scaler.fit(dt_prot_ctdd)
dt_prot_ctdd_norm= scaler.transform(dt_prot_ctdd)
dt_prot_ctdd_norm=pd.DataFrame(dt_prot_ctdd_norm)
dt_prot_ctdd_norm.tail()

,0,1,2,3,4,5,6,7,8,9,...,95,96,97,98,99,100,101,102,103,104
534,0.002277,0.238898,0.459121,0.726486,0.998861,0.000455,0.246641,0.507629,0.754270,0.999317,...,0.002277,0.238898,0.459121,0.726486,0.998861,0.000228,0.253245,0.516056,0.754270,0.999089
535,0.006633,0.202322,0.459370,0.741294,0.990050,0.001658,0.286899,0.510779,0.776119,1.000000,...,0.006633,0.202322,0.459370,0.741294,0.990050,0.001658,0.268657,0.520730,0.786070,1.000000
536,0.010870,0.256988,0.501553,0.764752,1.000000,0.006988,0.263199,0.512422,0.753882,0.996894,...,0.010870,0.256988,0.501553,0.764752,1.000000,0.000776,0.232143,0.489130,0.729814,0.996894
537,0.003219,0.204936,0.477468,0.748927,1.000000,0.001073,0.271459,0.541845,0.752146,0.996781,...,0.003219,0.204936,0.477468,0.748927,1.000000,0.001073,0.283262,0.576180,0.802575,0.996781
538,0.013072,0.225490,0.464052,0.754902,1.000000,0.003268,0.303922,0.516340,0.702614,0.993464,...,0.013072,0.225490,0.464052,0.754902,1.000000,0.003268,0.261438,0.470588,0.683007,0.993464

In [158]:
dt_prot_ctdd.describe()

,prop1.G1.residue0,prop1.G1.residue25,prop1.G1.residue50,prop1.G1.residue75,prop1.G1.residue100,prop1.G2.residue0,prop1.G2.residue25,prop1.G2.residue50,prop1.G2.residue75,prop1.G2.residue100,...,prop7.G2.residue0,prop7.G2.residue25,prop7.G2.residue50,prop7.G2.residue75,prop7.G2.residue100,prop7.G3.residue0,prop7.G3.residue25,prop7.G3.residue50,prop7.G3.residue75,prop7.G3.residue100
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,...,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,1.609541,25.877248,50.215269,74.729910,99.422574,0.896524,24.124251,49.417691,74.079900,99.287398,...,1.609541,25.877248,50.215269,74.729910,99.422574,0.489711,24.406475,49.641899,74.256327,98.906433
std,2.400846,4.701713,5.468928,4.830260,1.127033,1.597433,4.000901,4.635272,3.484095,1.879812,...,2.400846,4.701713,5.468928,4.830260,1.127033,1.478245,4.527628,5.017281,4.401675,2.310097
min,0.028185,4.878049,25.000000,47.058824,87.500000,0.042277,10.937500,32.314410,56.097561,78.378378,...,0.028185,4.878049,25.000000,47.058824,87.500000,0.014092,8.108108,30.000000,43.243243,78.378378
25%,0.453697,22.745008,47.493922,72.819473,99.343545,0.326797,21.893675,47.091359,72.271780,99.432614,...,0.453697,22.745008,47.493922,72.819473,99.343545,0.125628,22.011032,47.055210,72.052748,99.004033
50%,0.854701,25.790754,50.548246,75.285171,99.729364,0.500000,24.537037,49.777778,74.290484,99.806576,...,0.854701,25.790754,50.548246,75.285171,99.729364,0.208333,24.890830,50.000000,74.552684,99.702381
75%,1.883446,28.665208,53.107513,77.407825,100.000000,0.871464,26.629855,51.896815,76.056338,100.000000,...,1.883446,28.665208,53.107513,77.407825,100.000000,0.350877,27.162978,52.412106,76.823130,100.000000
max,35.135135,51.351351,77.000000,90.163934,100.000000,21.739130,39.130435,59.931507,86.189258,100.000000,...,35.135135,51.351351,77.000000,90.163934,100.000000,20.312500,40.839695,69.117647,87.931034,100.000000

In [159]:
dt_prot_ctdd_norm.describe()

,0,1,2,3,4,5,6,7,8,9,...,95,96,97,98,99,100,101,102,103,104
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,...,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,0.016095,0.258772,0.502153,0.747299,0.994226,0.008965,0.241243,0.494177,0.740799,0.992874,...,0.016095,0.258772,0.502153,0.747299,0.994226,0.004897,0.244065,0.496419,0.742563,0.989064
std,0.024008,0.047017,0.054689,0.048303,0.011270,0.015974,0.040009,0.046353,0.034841,0.018798,...,0.024008,0.047017,0.054689,0.048303,0.011270,0.014782,0.045276,0.050173,0.044017,0.023101
min,0.000282,0.048780,0.250000,0.470588,0.875000,0.000423,0.109375,0.323144,0.560976,0.783784,...,0.000282,0.048780,0.250000,0.470588,0.875000,0.000141,0.081081,0.300000,0.432432,0.783784
25%,0.004537,0.227450,0.474939,0.728195,0.993435,0.003268,0.218937,0.470914,0.722718,0.994326,...,0.004537,0.227450,0.474939,0.728195,0.993435,0.001256,0.220110,0.470552,0.720527,0.990040
50%,0.008547,0.257908,0.505482,0.752852,0.997294,0.005000,0.245370,0.497778,0.742905,0.998066,...,0.008547,0.257908,0.505482,0.752852,0.997294,0.002083,0.248908,0.500000,0.745527,0.997024
75%,0.018834,0.286652,0.531075,0.774078,1.000000,0.008715,0.266299,0.518968,0.760563,1.000000,...,0.018834,0.286652,0.531075,0.774078,1.000000,0.003509,0.271630,0.524121,0.768231,1.000000
max,0.351351,0.513514,0.770000,0.901639,1.000000,0.217391,0.391304,0.599315,0.861893,1.000000,...,0.351351,0.513514,0.770000,0.901639,1.000000,0.203125,0.408397,0.691176,0.879310,1.000000

In [161]:
dt_prot0[dt_prot0.isna().any(axis=1)]

,A,R,N,D,C,E,Q,G,H,I,...,Xc2.lambda.22,Xc2.lambda.23,Xc2.lambda.24,Xc2.lambda.25,Xc2.lambda.26,Xc2.lambda.27,Xc2.lambda.28,Xc2.lambda.29,Xc2.lambda.30,Unnamed: 217
141,0.085938,0.062500,0.070312,0.054688,0.000000,0.023438,0.039062,0.132812,0.015625,0.054688,...,0.025708,0.025389,0.026565,0.022446,0.025612,0.024703,0.027108,0.029234,0.025727,6VYO
143,0.092486,0.011561,0.098266,0.052023,0.017341,0.046243,0.017341,0.080925,0.034682,0.034682,...,0.024131,0.023637,0.022825,0.022615,0.021945,0.022720,0.023902,0.023185,0.022319,6W02
144,0.094017,0.051282,0.068376,0.051282,0.025641,0.025641,0.034188,0.076923,0.000000,0.017094,...,0.020551,0.025734,0.022343,0.022302,0.025266,0.026860,0.026186,0.023924,0.028591,6W4B
146,0.098592,0.014085,0.056338,0.049296,0.091549,0.028169,0.042254,0.091549,0.021127,0.028169,...,0.022727,0.022567,0.023859,0.024772,0.023807,0.022421,0.023421,0.022240,0.023366,6W4H:B

In [164]:
dt_prot0=dt_prot0.fillna(0)

In [165]:
from sklearn.preprocessing import Normalizer
scaler= Normalizer(norm='max')
scaler.fit(dt_prot_paac1)
dt_prot_paac1_norm= scaler.transform(dt_prot_paac1)
dt_prot_paac1_norm=pd.DataFrame(dt_prot_paac1_norm)
dt_prot_paac1_norm.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
534,0.797674,0.339535,0.486047,0.555814,0.311628,0.411628,0.337209,0.593023,0.193023,0.458140,0.990698,0.555814,0.220930,0.509302,0.395349,0.753488,0.730233,0.116279,0.455814,1.000000
535,0.633333,0.300000,0.650000,0.550000,0.133333,0.783333,0.500000,0.533333,0.366667,0.366667,1.000000,0.566667,0.350000,0.450000,0.450000,0.566667,0.533333,0.333333,0.466667,0.516667
536,0.757009,0.392523,0.822430,0.570093,0.280374,0.476636,0.616822,0.878505,0.242991,0.663551,1.000000,0.542056,0.102804,0.738318,0.588785,0.981308,0.887850,0.112150,0.495327,0.887850
537,0.771084,0.518072,0.674699,0.903614,0.349398,0.373494,0.337349,0.542169,0.325301,0.397590,1.000000,0.614458,0.301205,0.686747,0.361446,0.638554,0.734940,0.108434,0.698795,0.891566
538,0.586207,0.379310,0.724138,0.586207,0.413793,0.310345,0.482759,0.896552,0.241379,0.379310,1.000000,0.379310,0.344828,0.586207,0.448276,0.551724,0.827586,0.103448,0.379310,0.931034

In [166]:
dt_prot_paac1.describe()

,Xc1.A,Xc1.R,Xc1.N,Xc1.D,Xc1.C,Xc1.E,Xc1.Q,Xc1.G,Xc1.H,Xc1.I,Xc1.L,Xc1.K,Xc1.M,Xc1.F,Xc1.P,Xc1.S,Xc1.T,Xc1.W,Xc1.Y,Xc1.V
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,11.095963,8.296852,6.808743,8.151015,3.444223,10.248401,6.551536,10.567897,3.940647,8.132108,15.992773,9.249076,4.054771,7.198842,9.185954,12.274822,9.111763,2.161663,5.356928,11.100308
std,12.571074,7.504853,7.949832,8.449696,4.510115,9.631290,6.824993,10.332988,3.714532,8.326557,16.434756,9.740058,4.028625,7.688855,9.116128,14.424562,11.221890,2.172203,6.522284,12.785014
min,0.638144,0.000000,0.000000,0.000000,0.000000,0.500241,0.000000,0.000000,0.000000,0.000000,0.258636,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.295960
25%,4.474481,3.407395,2.694352,3.398102,1.266402,3.938433,2.500077,4.628328,1.572521,3.135962,7.559975,3.502931,1.686068,3.368270,3.558047,4.580241,3.681941,0.770846,2.452557,4.994626
50%,7.720429,6.544626,4.879652,6.152484,2.411365,7.396144,4.355066,7.841361,3.084994,6.344445,11.674952,7.212253,3.256574,5.481307,6.972590,8.517561,6.659350,1.621993,4.138839,8.194829
75%,13.047083,10.782293,8.304608,10.952218,4.348088,14.083018,8.505556,12.543352,5.366358,9.507855,19.471150,11.854337,5.439689,8.416156,11.792532,15.283088,10.729454,2.810095,6.807753,13.261889
max,132.655056,66.463724,104.598648,105.960609,61.560662,92.613386,65.101762,112.225632,39.496885,93.430563,181.958064,118.218263,45.761908,95.064917,74.635493,124.210894,143.550748,21.246600,91.251424,162.890602

In [167]:
dt_prot_paac1_norm.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,0.602119,0.477728,0.381008,0.467301,0.193539,0.584131,0.362702,0.619939,0.226083,0.479578,0.892504,0.544677,0.239591,0.422011,0.513807,0.642417,0.501966,0.125446,0.305590,0.629054
std,0.190190,0.169194,0.174665,0.165204,0.109972,0.211463,0.143234,0.221617,0.095988,0.198975,0.190191,0.217659,0.100341,0.156847,0.188316,0.207374,0.179885,0.070144,0.132397,0.188246
min,0.144068,0.000000,0.000000,0.000000,0.000000,0.098361,0.000000,0.000000,0.000000,0.000000,0.090909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.071429
25%,0.462912,0.363234,0.266667,0.359582,0.125000,0.432432,0.258098,0.445437,0.163265,0.346990,0.851761,0.397494,0.166667,0.313579,0.400000,0.500000,0.388889,0.077524,0.225340,0.508475
50%,0.604938,0.461538,0.360000,0.452055,0.176471,0.574074,0.354839,0.608108,0.227273,0.456693,1.000000,0.555814,0.237705,0.412698,0.500000,0.621622,0.483871,0.116667,0.301205,0.633333
75%,0.705400,0.574385,0.472222,0.564145,0.243573,0.737986,0.454545,0.771930,0.279991,0.604409,1.000000,0.680749,0.305500,0.515090,0.625933,0.786190,0.607919,0.165525,0.380952,0.762842
max,1.000000,1.000000,1.000000,1.000000,0.928571,1.000000,0.916667,1.000000,0.782609,1.000000,1.000000,1.000000,0.666667,1.000000,1.000000,1.000000,1.000000,0.444444,0.714286,1.000000

In [168]:
dt_prot_paac2.describe()

,Xc2.lambda.1,Xc2.lambda.2,Xc2.lambda.3,Xc2.lambda.4,Xc2.lambda.5,Xc2.lambda.6,Xc2.lambda.7,Xc2.lambda.8,Xc2.lambda.9,Xc2.lambda.10,...,Xc2.lambda.21,Xc2.lambda.22,Xc2.lambda.23,Xc2.lambda.24,Xc2.lambda.25,Xc2.lambda.26,Xc2.lambda.27,Xc2.lambda.28,Xc2.lambda.29,Xc2.lambda.30
count,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,...,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000,539.000000
mean,0.024483,0.025042,0.024296,0.024235,0.024554,0.024610,0.024360,0.024376,0.024601,0.024543,...,0.024805,0.024892,0.024903,0.024768,0.024848,0.024734,0.024729,0.024742,0.024571,0.024848
std,0.001314,0.001420,0.001289,0.001388,0.001170,0.001198,0.001241,0.001164,0.001114,0.001196,...,0.001188,0.001324,0.001316,0.001286,0.001174,0.001111,0.001615,0.001388,0.001350,0.001250
min,0.020031,0.019937,0.018766,0.015695,0.020405,0.018869,0.016978,0.018057,0.021059,0.017870,...,0.019639,0.020551,0.018365,0.013241,0.019731,0.020826,0.015883,0.016771,0.017766,0.015388
25%,0.023816,0.024210,0.023670,0.023519,0.023886,0.024062,0.023644,0.023679,0.024048,0.023906,...,0.024019,0.024070,0.024268,0.024124,0.024090,0.024129,0.024123,0.024059,0.023929,0.024245
50%,0.024511,0.025142,0.024375,0.024285,0.024650,0.024570,0.024360,0.024366,0.024608,0.024557,...,0.024760,0.024832,0.024925,0.024760,0.024824,0.024670,0.024853,0.024668,0.024656,0.024855
75%,0.025231,0.025984,0.024917,0.025082,0.025324,0.025249,0.025078,0.025113,0.025300,0.025254,...,0.025564,0.025670,0.025506,0.025418,0.025517,0.025334,0.025471,0.025435,0.025364,0.025459
max,0.030153,0.029224,0.032285,0.027864,0.028409,0.028957,0.029077,0.029016,0.028454,0.030115,...,0.030069,0.030624,0.031651,0.032917,0.029765,0.029272,0.036862,0.032007,0.030930,0.032532

In [169]:
dt_prot_norm=pd.concat([dt_prot_aac,dt_prot_ctdc,dt_prot_ctdt,dt_prot_ctdd_norm,dt_prot_paac1_norm,dt_prot_paac2,dt_prot_id], axis=1)
dt_prot_norm.tail()

,A,R,N,D,C,E,Q,G,H,I,...,Xc2.lambda.22,Xc2.lambda.23,Xc2.lambda.24,Xc2.lambda.25,Xc2.lambda.26,Xc2.lambda.27,Xc2.lambda.28,Xc2.lambda.29,Xc2.lambda.30,Unnamed: 217
534,0.078114,0.033250,0.047597,0.054430,0.030517,0.040310,0.033022,0.058073,0.018902,0.044864,...,0.023736,0.024067,0.024042,0.024233,0.023815,0.023540,0.024581,0.023828,0.023941,K4LC41_9BETC
535,0.063018,0.029851,0.064677,0.054726,0.013267,0.077944,0.049751,0.053068,0.036484,0.036484,...,0.024756,0.024148,0.025199,0.024554,0.023132,0.024701,0.025072,0.025616,0.025272,6M0J:A
536,0.062888,0.032609,0.068323,0.047360,0.023292,0.039596,0.051242,0.072981,0.020186,0.055124,...,0.024046,0.024760,0.023859,0.024653,0.024845,0.022532,0.023180,0.024130,0.024999,6VSB
537,0.068670,0.046137,0.060086,0.080472,0.031116,0.033262,0.030043,0.048283,0.028970,0.035408,...,0.024421,0.024701,0.024124,0.024537,0.024475,0.023487,0.025516,0.025637,0.024120,YP_009725307.1
538,0.055556,0.035948,0.068627,0.055556,0.039216,0.029412,0.045752,0.084967,0.022876,0.035948,...,0.024021,0.022053,0.024425,0.023855,0.024451,0.023342,0.023351,0.021879,0.025722,6LU7

In [170]:
dt_prot1_norm=dt_prot_norm.iloc[:163, :]
dt_prot1_norm.tail()

,A,R,N,D,C,E,Q,G,H,I,...,Xc2.lambda.22,Xc2.lambda.23,Xc2.lambda.24,Xc2.lambda.25,Xc2.lambda.26,Xc2.lambda.27,Xc2.lambda.28,Xc2.lambda.29,Xc2.lambda.30,Unnamed: 217
158,0.062654,0.039312,0.066339,0.052826,0.009828,0.070025,0.047912,0.052826,0.020885,0.049140,...,0.025174,0.024556,0.025749,0.025268,0.024530,0.025235,0.025944,0.025898,0.024697,6M17:B
159,0.053812,0.049327,0.094170,0.040359,0.040359,0.031390,0.031390,0.067265,0.004484,0.040359,...,0.022997,0.024688,0.025807,0.026951,0.026748,0.022082,0.025554,0.024724,0.024144,6M17:E
160,0.062888,0.032609,0.068323,0.047360,0.023292,0.039596,0.051242,0.072981,0.020186,0.055124,...,0.024046,0.024760,0.023859,0.024653,0.024845,0.022532,0.023180,0.024130,0.024999,6VSB
161,0.063652,0.030151,0.065327,0.055276,0.013400,0.078727,0.050251,0.053601,0.026801,0.036851,...,0.024783,0.024166,0.025198,0.024556,0.023144,0.024723,0.025117,0.025661,0.025337,6VW1:A
162,0.068670,0.046137,0.060086,0.080472,0.031116,0.033262,0.030043,0.048283,0.028970,0.035408,...,0.024421,0.024701,0.024124,0.024537,0.024475,0.023487,0.025516,0.025637,0.024120,YP_009725307.1

In [171]:
dt_prot0_norm=dt_prot_norm.iloc[163:, :]
dt_prot0_norm.head()

,A,R,N,D,C,E,Q,G,H,I,...,Xc2.lambda.22,Xc2.lambda.23,Xc2.lambda.24,Xc2.lambda.25,Xc2.lambda.26,Xc2.lambda.27,Xc2.lambda.28,Xc2.lambda.29,Xc2.lambda.30,Unnamed: 217
163,0.061576,0.071429,0.039409,0.071429,0.009852,0.071429,0.051724,0.059113,0.012315,0.083744,...,0.025563,0.025422,0.025610,0.024049,0.024583,0.025029,0.023379,0.022667,0.025633,IF4A1_HUMAN
164,0.058968,0.066339,0.041769,0.066339,0.009828,0.078624,0.049140,0.066339,0.014742,0.085995,...,0.026131,0.025171,0.026185,0.023717,0.024414,0.024885,0.023260,0.022994,0.025815,IF4A2_HUMAN
165,0.063260,0.077859,0.029197,0.068127,0.012165,0.070560,0.048662,0.058394,0.012165,0.082725,...,0.026004,0.025915,0.025820,0.023958,0.023814,0.026647,0.023815,0.023139,0.025798,IF4A3_HUMAN
166,0.063354,0.038509,0.067081,0.053416,0.009938,0.069565,0.047205,0.053416,0.019876,0.049689,...,0.025133,0.024518,0.025943,0.025360,0.024485,0.025101,0.025802,0.025970,0.024860,ACE2_HUMAN
167,0.052083,0.062500,0.027083,0.058333,0.014583,0.102083,0.035417,0.062500,0.027083,0.041667,...,0.025027,0.024739,0.025586,0.023979,0.024970,0.024984,0.023537,0.025452,0.023987,AKT1_HUMAN

In [190]:
dt_comp1['key'] = 1#mbaFika
dt_comp2['key'] = 1#mbaLinda
dt_comp0['key'] = 1#Latih
dt_prot0['key'] = 1#Uji
dt_prot1['key'] = 1#Latih
dt_comp_gabung['key'] =1 #Mba Lin+Fik

In [196]:
df = pd.merge(dt_comp0,dt_prot1,on='key').drop('key',axis=1)
df.to_csv("addedlatih_dip.csv", header=False,index=False) 
print(df.isnull().sum().max())
df.tail()

0

,0,1,2,3,4,5,6,7,8,9,...,KV,MV,FV,PV,SV,TV,WV,YV,VV,#
20995,LMT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.003108,0.000777,0.003885,0.002331,0.003885,0.002331,0.003885,0.000000,0.002331,6VSB:A
20996,LMT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.003125,0.000781,0.003906,0.002344,0.003906,0.002344,0.003906,0.000000,0.002344,6VXX:A
20997,LMT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.002050,0.001139,0.000911,0.001595,0.002961,0.004556,0.004328,0.000228,0.002050,K4LC41_9BETC
20998,LMT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.004296,0.003222,0.002148,0.004296,0.003222,0.003222,0.003222,0.002148,0.004296,YP_009725307.1
20999,LMT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.000000,0.003185,0.003185,0.003185,0.000000,0.006369,0.003185,0.000000,0.006369,PLpro_SARS-CoV-2

In [197]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,KV,MV,FV,PV,SV,TV,WV,YV,VV,#
0,44447656,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.004938,0.002469,0.002469,0.000000,0.000000,0.002469,0.0,0.000000,0.004938,IF4A1_HUMAN
1,44447656,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.004926,0.000000,0.004926,0.000000,0.000000,0.004926,0.0,0.000000,0.004926,IF4A2_HUMAN
2,44447656,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.004878,0.000000,0.004878,0.000000,0.002439,0.002439,0.0,0.000000,0.004878,IF4A3_HUMAN
3,44447656,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.004975,0.002488,0.003731,0.002488,0.003731,0.002488,0.0,0.002488,0.006219,ACE2_HUMAN
4,44447656,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.002088,0.000000,0.002088,0.000000,0.002088,0.004175,0.0,0.000000,0.004175,AKT1_HUMAN

In [192]:
df = pd.merge(dt_comp1,dt_prot0,on='key').drop('key',axis=1)
df.to_csv("added_ujimbafikanorm_dip.csv", header=False,index=False)

In [193]:
df = pd.merge(dt_comp2,dt_prot0,on='key').drop('key',axis=1)
df.to_csv("added_ujimbalindanorm_dip.csv", header=False,index=False)

In [194]:
df = pd.merge(dt_comp_gabung,dt_prot0,on='key').drop('key',axis=1)
df.to_csv("added_ujigabungnorm_dip.csv", header=False,index=False)

In [179]:
df.head()

,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,...,Xc2.lambda.22,Xc2.lambda.23,Xc2.lambda.24,Xc2.lambda.25,Xc2.lambda.26,Xc2.lambda.27,Xc2.lambda.28,Xc2.lambda.29,Xc2.lambda.30,Unnamed: 217
0,Syringaresinol,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.025563,0.025422,0.025610,0.024049,0.024583,0.025029,0.023379,0.022667,0.025633,IF4A1_HUMAN
1,Syringaresinol,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.026131,0.025171,0.026185,0.023717,0.024414,0.024885,0.023260,0.022994,0.025815,IF4A2_HUMAN
2,Syringaresinol,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.026004,0.025915,0.025820,0.023958,0.023814,0.026647,0.023815,0.023139,0.025798,IF4A3_HUMAN
3,Syringaresinol,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.025133,0.024518,0.025943,0.025360,0.024485,0.025101,0.025802,0.025970,0.024860,ACE2_HUMAN
4,Syringaresinol,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.025027,0.024739,0.025586,0.023979,0.024970,0.024984,0.023537,0.025452,0.023987,AKT1_HUMAN

In [17]:
#np.savetxt("herball+added.csv",df,fmt=["%s"]*(1284), delimiter=";")
np.savetxt("herball+added.xlsx",df,fmt=["%s"]*(1284))

In [14]:
df.to_excel("herball+added.xlsx", header=None, index=None, engine='xlsxwriter')

KeyboardInterrupt:

In [ ]:
#df.to_csv("herball.csv")

In [14]:
def combine_data(X,Y,Z):
    compound = X
    protein = Y
    dt_prot = pd.read_csv(protein, delimiter=";")
    dt_comp = pd.read_excel(compound, header=None)
    prots = dt_prot.values
    comps = dt_comp.values

    cxp = concate_data(comps,prots)
    print(dt_prot.shape)
    print(dt_comp.shape)
    print(dt_comp.shape[1]+dt_prot.shape[1])
    np.savetxt(Z,cxp,fmt=["%s"]*(1283), delimiter=";")
    return cxp ### ["%d",] ["%.5f",]

def concate_data(A,B):
    row1,col1 = A.shape
    row2,col2 = B.shape

    out = np.zeros((row1,row2,col1+col2), dtype = B.dtype)
    out[:,:,:col1] = A[:,None,:]
    out[:,:,col1:] = B

        
    return out.reshape(row1*row2,-1)

In [16]:
#dt_comp = pd.read_excel("newfp.xlsx", header=None)

In [17]:
#dt_comp.head()

In [20]:
dt=combine_data("newfp.xlsx","newdip.csv","newint.csv")

(371, 401)
(392, 882)
1283

In [ ]:
label1 = np.ones( (r1.shape[0],1) )
label2 = np.ones( (r2.shape[0],1) ) * -1
data = np.concatenate((r1, r2))
labels = np.concatenate((label1, label2))

In [8]:
pd.DataFrame({'A': ['a', 'b', 'c', 'd', 'e'],'B': [5, 6, 7, 5, 9],'C': ['2a', '2b', '2c', '2d', '2e']})

   A  B   C
0  a  5  2a
1  b  6  2b
2  c  7  2c
3  d  5  2d
4  e  9  2e